CREATE TABLE TABELA_DE_VENDEDORES (MATRICULA varchar(5), NOME varchar(100), COMISSAO float);

CREATE TABLE Cliente2 
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT, PRIMEIRA_COMPRA BIT(1))



CREATE TABLE PRODUTO
( PRODUTO VARCHAR(20) NULL,
NOME VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
SABOR VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL); 



USE sucos2;

DROP TABLE tabela_de_vendedores;

INSERT INTO produto ( PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
VALUES ('1040107', 'Light-350ml-melancia', 'Lata', '350ml','Melancia', 4.56);

INSERT INTO tabela_de_vendedores (MATRICULA,NOME,COMISSAO)
VALUES ('00233', 'JOAO GERALDO DA FONSECA',0.10);

select * from tabela_de_vendedores;


INSERT INTO tabela_de_vendedores (MATRICULA,NOME,COMISSAO)
VALUES ('00236', 'CLAUDIA MORAIS',0.08);

USE sucos2;

UPDATE tabela_de_vendedores SET COMISSAO = 0.10
WHERE MATRICULA = '00233';


USE sucos2;

DELETE FROM tabela_de_vendedores WHERE MATRICULA = '00233';

select * from tabela_de_vendedores


USE sucos2;

ALTER TABLE produto ADD primary key (PRODUTO);
